export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

//JOB POSTINGS
export const GET_POSTING = 'GET_POSTING';
export const GET_POSTING_REQUEST = 'GET_POSTING_REQUEST';
export const GET_POSTING_FAILURE = 'GET_POSTING_FAILURE';
export const GET_POSTING_SUCCESS = 'GET_POSTING_SUCCESS';

//STAFF ENTRIES
export const GET_STAFF = 'GET_STAFF';
export const GET_STAFF_REQUEST = 'GET_STAFF_REQUEST';
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS';
export const GET_STAFF_FAILURE = 'GET_STAFF_FAILURE';

//USER JOBS
export const GET_USER_JOBS = 'GET_USER_JOBS';
export const GET_USER_JOBS_REQUEST = 'GET_USER_JOBS_REQUEST';
export const GET_USER_JOBS_SUCCESS = 'GET_USER_JOBS_SUCCESS';
export const GET_USER_JOBS_FAILURE = 'GET_USER_JOBS_FAILURE';

//STATUS TRACKING
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_POSTING = 'DESTROY_POSTING';


//CLIENT SIDE FILTERING
export const TYPING = 'TYPING';

//LOGIN FLOW
export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

//MODALS
export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
