name: scrapy
dependencies:
- cffi=1.6.0=py27_0
- cryptography=1.3.2=py27_0
- cssselect=0.9.1=py27_0
- enum34=1.1.6=py27_0
- idna=2.1=py27_0
- ipaddress=1.0.16=py27_0
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- lxml=3.6.0=py27_0
- nose=1.3.7=py27_1
- openssl=1.0.2h=0
- pip=8.1.1=py27_1
- pyasn1=0.1.9=py27_0
- pycparser=2.14=py27_0
- pymongo=3.0.3=py27_0
- pyopenssl=0.15.1=py27_2
- python=2.7.11=0
- queuelib=1.2.2=py27_0
- readline=6.2=2
- scrapy=1.0.3=py27_0
- setuptools=21.2.1=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- twisted=16.2.0=py27_0
- w3lib=1.12.0=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- zope.interface=4.1.3=py27_0
- pip:
  - attrs==16.0.0
  - beautifulsoup4==4.4.1
  - bs4==0.0.1
  - cycler==0.10.0
  - elasticsearch==2.3.0
  - jinja2==2.8
  - markupsafe==0.23
  - matplotlib==1.5.1
  - mpld3==0.2
  - nltk==3.2.1
  - numpy==1.11.0
  - pandas==0.18.1
  - pyasn1-modules==0.0.8
  - pyparsing==2.1.4
  - python-dateutil==2.5.3
  - pytz==2016.4
  - redis==2.10.5
  - requests==2.10.0
  - scikit-learn==0.17.1
  - scipy==0.17.1
  - scrapy-redis==0.6.0
  - scrapyelasticsearch==0.7
  - selenium==2.53.2
  - service-identity==16.0.0
  - sklearn==0.0
  - urllib3==1.15.1

